 version: '2'
 volumes:
  collected_static: {}
 services:
  cts_django:
    build: .
    expose:
    - "8080"
    volumes:
    - collected_static:/src/collected_static
  nginx:
#    restart: always
    image: funkswing/nginx-uwsgi-django
    ports:
    - "80:80"
    - "443:443"
    links:  # Same as depends_on cts_django, but also sets the hostname at which this service can reach the linked service
    - cts_django:uwsgi  # Nginx.conf can reference "cts_django" service with the hostname 'uwsgi' or 'cts_django'
    volumes_from:
    - cts_django:ro  # Mount all volumes from "cts_django" to NGINX, so it can access the collected static files